spring:
  application:
    name: todo-app
  datasource:
    driver-class-name: org.h2.Driver
    username: a
    password: a
    url: "jdbc:h2:mem:todoapp;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

# habilitar/deshabilitar api-docs - swagger-ui
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
# definir la ruta de swagger-ui
    path: /doc/swagger-ui.html
# seleccionar paquetes, clases a escanear
  pathsToMatch: /tasks/**, /support/**
